name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test  # 테스트를 활성화하려면 주석 해제

  deploy:
    runs-on: ubuntu-latest
    needs: build # 빌드가 완료된 후 배포 진행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd /home/guest/hm-blog/frontend || exit
            git pull origin main || exit  # 최신 코드 가져오기
            npm ci || exit  # 의존성 설치
            npm run build || exit  # 빌드
            pm2 restart blog-with-m || exit  # 애플리케이션 재시작
          EOF
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
